### ISSUE TITLE
RPC call failed, y [RpcError]: getaddrinfo EBUSY mainnet-rpc-node-0001.nkn.org

### ISSUE THREAD

**Issue by SteveCruise** [nknorg/nkn-sdk-js#125]
不断反复报这个错，导致连不上，网址可以ping通，环境是Node.js 16 / arm嵌入式设备，没有用tls

RPC call failed, y [RpcError]: getaddrinfo EBUSY mainnet-rpc-node-0001.nkn.org
    at h (/tmp/app.js:2:1187963)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async t.default._connect (/tmp/app.js:2:1078300)
RPC call failed, y [RpcError]: getaddrinfo EBUSY mainnet-rpc-node-0001.nkn.org
    at h (/tmp/app.js:2:1187963)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async t.default._connect (/tmp/app.js:2:1078300)
RPC call failed, y [RpcError]: getaddrinfo EBUSY mainnet-rpc-node-0001.nkn.org
    at h (/tmp/app.js:2:1187963)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async t.default._connect (/tmp/app.js:2:1078300)
RPC call failed, y [RpcError]: getaddrinfo EBUSY mainnet-rpc-node-0001.nkn.org
    at h (/tmp/app.js:2:1187963)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async t.default._connect (/tmp/app.js:2:1078300)

报错位置是nkn.js的`getAddr(this.addr, this.options)`
```js
for (let i = 0; i < 3; i++) {
      try {
        res = await getAddr(this.addr, this.options);
      } catch (e) {
        error = e;
        continue;
      }

      this._newWsAddr(res);

      return;
    }
``` 
应该是这里
https://github.com/nknorg/nkn-sdk-js/blob/fba187239b6a2ea8993ae3cd37458f13bb5a7db1/src/client/client.js#L150

**Comment by yilunzhang** [comment]
我查了一下，这个看起来应该是你设备上的问题，比如文件句柄耗尽或者其他问题。可以参考这个链接 https://github.com/nodejs/help/issues/2390 我建议你可以先尝试增加一下文件句柄限制

**Comment by SteveCruise** [comment]
谢谢大神！我再想想办法
