### ISSUE TITLE
Create a node.js duplex stream

### ISSUE THREAD

**Issue by sce9sc** [nknorg/nkn-sdk-js#97]
I need some help please. 
I am trying really hard to create a tunnel in node.js but I am stuck with creating a duplex stream from 
session.getReadableStream() and session.getWritableStream() in order to pipe it to a tcp server and client

I know it is too much to ask . If someone can help i'll really appreciate it.

**Comment by yilunzhang** [comment]
Have you checked this sample app: https://github.com/nknorg/nftp-js/blob/master/main.js

**Comment by sce9sc** [comment]
I have but is not that straight forward

What I have so far is this 

```
const streams = require("stream");
const webStreams =require('web-streams-node');
const webstreamsPoly = require("web-streams-polyfill/dist/polyfill.min");
const duplex2 =  require('duplex-to')


const WritableStream = webstreamsPoly.WritableStream
const ReadableStream = webstreamsPoly.ReadableStream

var toWebReadableStream = webStreams.toWebReadableStream;
const Readable = streams.Readable;

const readable = duplex2.readable;





class NodeReadable extends Readable {
    constructor(webStream, options) {
        super(options);
        this._webStream = webStream;
        this._reader = webStream.getReader();
        this._reading = false;
    }
  
    _read(size) {
        if (this._reading) {
            return;
        }
        this._reading = true;
        const doRead = () => {
            this._reader.read()
                .then(res => {
                    if (this._doneReading) {
                        this._reading = false;
                        this._reader.releaseLock();
                        this._doneReading();
                    }
                    if (res.done) {
                        this.push(null);
                        this._reading = false;
                        this._reader.releaseLock();
                        return;
                    }
                    if (this.push(res.value)) {
                        return doRead(size);
                    } else {
                        this._reading = false;
                        // this._reader.releaseLock();
                        // this._reader = this._webStream.getReader();
                    }
                });
        };
        doRead();
    }
    
    _destroy(err, callback) {
        if (this._reading) {
            const promise = new Promise(resolve => {
                this._doneReading = resolve;
            });
            promise.then(() => this._handleDestroy(err, callback));
        } else {
            this._handleDestroy(err, callback);
        }
    }
        
    _handleDestroy(err, callback) {
        this._webStream.cancel();
        super._destroy(err, callback);
    }
  }
  
  function readableWebToNode(webStream, options) {
    return new NodeReadable(webStream, options);
  }
  
  const myPipeNodeToWriteWeb = (nodeRead , webWrite)=>{
    const readPass = readable(nodeRead)
    const werRead1 = toWebReadableStream(readPass)
    werRead1.pipeTo(webWrite)
  }
  
  const mypipeReadToWriteNode = (myRead, myWrite)=>{
    myRead.pipe(myWrite)
  }   
  
  const myPipe = (s, duplex)=>{
    s.ReadableStream = ReadableStream
    s.WritableStream = WritableStream
    const rStream  = s.getReadableStream()
    const wStream = s.getWritableStream(true)
    const RStreamNode = readableWebToNode(rStream, {})
    myPipeNodeToWriteWeb(duplex, wStream)
    mypipeReadToWriteNode(RStreamNode,duplex)
  }


  module.exports = { myPipe };
```

**Comment by yilunzhang** [comment]
> const webstreamsPoly = require("web-streams-polyfill/dist/polyfill.min");

From what I understand, this library is meant to be used in browser as a polyfill for native stream. You seem to use it in the other way?

**Comment by sce9sc** [comment]
You are correct . I want to use it node.js and since I don't know how to get a duplex from nkn-sdk session I have tried to create one using the above.

The documentation only provides a way to get WebReadable and WebWritable Streams . 

The end goal is to create a Socket server that I can pipe it to the session . 

Are there any alternatives ? Apart from pushing and writing  from / to the session. 

The other problem that I have is the reader and writer Locks  and occasionally

```
Message handler error: NotHandshakeError: first packet is not handshake packet
    at Session.accept (/Users/sce9sc/Documents/Work/capacitorTest/movies/chatService/node_modules/@nkn/ncp/lib/session.js:564:15)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:434:9)
    at async MultiClient._handleSessionMsg (/Users/sce9sc/Documents/Work/capacitorTest/movies/chatService/node_modules/nkn-sdk/lib/multiclient/multiclient.js:357:7)
    at async /Users/sce9sc/Documents/Work/capacitorTest/movies/chatService/node_modules/nkn-sdk/lib/multiclient/multiclient.js:181:13
    at async /Users/sce9sc/Documents/Work/capacitorTest/movies/chatService/node_modules/nkn-sdk/lib/client/client.js:569:22
    at async Promise.all (index 0)
    at async Client._handleInboundMsg (/Users/sce9sc/Documents/Work/capacitorTest/movies/chatService/node_modules/nkn-sdk/lib/client/client.js:567:27)
    at async Client._handleMsg (/Users/sce9sc/Documents/Work/capacitorTest/movies/chatService/node_modules/nkn-sdk/lib/client/client.js:514:16)
    at async WebSocket.ws.onmessage (/Users/sce9sc/Documents/Work/capacitorTest/movies/chatService/node_modules/nkn-sdk/lib/client/client.js:700:25)

```

**Comment by yilunzhang** [comment]
Which node version are you using? I just did some search and found this: https://nodejs.org/api/stream.html#streamduplexfromwebpair-options

**Comment by sce9sc** [comment]
Unfortunately  I can not use node 18, but even so, I tried in the past the node 17 api and still could not make it to work . I tried the fromWeb, but since I had to polyfill It did not work

**Comment by yilunzhang** [comment]
I tried in node 17/18 and it worked perfectly fine in both node versions, no need to use polyfill at all:

```javascript
const stream = require('node:stream');
const { ReadableStream, WritableStream } = require('node:stream/web');

let session = client.dial(...);
session.ReadableStream = ReadableStream;
session.WritableStream = WritableStream;
let duplex = stream.Duplex.fromWeb({
  readable: session.getReadableStream(),
  writable: session.getWritableStream(),
});
```

I tested read and write of the duplex, both working well

**Comment by sce9sc** [comment]
Sorry for the late reply . Thank you . I just tried it and it worked .

It would be nice if there was also a way to use the above in the browser.

Thank you again

**Comment by yilunzhang** [comment]
`session.getReadableStream()` and `session.getWritableStream()` can be used in browser. As for the duplex, we will probably need to wait for browsers to support that (unless they did already)...
